wip

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -49,7 +49,6 @@ services:
 ## INGESTAO
 ############################
 
-
   airflow-webserver:
     <<: *airflow-common
     container_name: airflow-webserver
@@ -159,7 +158,6 @@ services:
       retries: 5
       start_period: 30s
 
-
 ############################
 ## DATABASE
 ############################
@@ -176,28 +174,6 @@ services:
     volumes:
       - ./util:/util    
 
-  presto:
-    platform: linux/amd64
-    image: prestodb/presto
-    hostname: presto
-    container_name: presto
-    volumes: 
-      - ./presto/etc/catalog:/opt/presto-server/etc/catalog/
-      - ./presto/etc/catalog:/opt/presto/etc/catalog/
-      - ./presto/etc/catalog:/etc/catalog/ 
-      - ./presto/etc/hadoop:/hadoop 
-      - ./util:/util
-    ports:
-      - 18080:8080
-    depends_on:
-      - hive
-
-    deploy:
-      resources:
-        limits:
-          memory: 2g
-          #cpus: '0.2'
-
   db:
     image: postgres:16
     platform: linux/amd64
@@ -213,55 +189,7 @@ services:
     volumes:
       - ./postgres/volume:/var/lib/postgresql/data
       - ./util:/util
-
-  # adminer:
-  #   image: adminer
-  #   platform: linux/amd64
-  #   container_name: adminer
-  #   hostname: adminer
-  #   ports:
-  #     - 28080:8080
-      
-  # mysql:
-  #   image: mysql
-  #   platform: linux/amd64
-  #   container_name: mysql
-  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
-  #   # (this is just an example, not intended to be a production configuration)
-  #   command: --default-authentication-plugin=mysql_native_password
-  #   restart: always
-  #   environment:
-  #     MYSQL_ROOT_PASSWORD: root
-  #   ports:
-  #     - 13306:3306
-  #   volumes:
-  #     - ./mysql/db:/var/lib/mysql
-
-
-  hive:
-    hostname: hive
-    #image: apache/hive:4.0.0-beta-1
-    image: fjardim/mds-hive
-    platform: linux/amd64
-    container_name: hive
-    environment:
-      AWS_ACCESS_KEY_ID: datalake
-      AWS_SECRET_ACCESS_KEY: datalake
-      HIVE_CUSTOM_CONF_DIR: "/hive_custom_conf"
-      SERVICE_NAME: hiveserver2
-      SERVICE_OPTS: "-Dhive.metastore.uris=thrift://metastore:9083" 
-      IS_RESUME: "true"
-      #HIVE_VERSION: "3.1.3"
-    ports:
-       - "10000:10000"
-       - "10002:10002"
-    depends_on:
-      - metastore
-    user: root
-    volumes:
-       - ./hive/conf:/hive_custom_conf
-       - ./util:/util
-          
+     
   metastore:
     hostname: metastore
     platform: linux/amd64
@@ -282,7 +210,6 @@ services:
     depends_on:
         - db
 
-
   clickhouse:
     image: clickhouse/clickhouse-server
     platform: linux/amd64
@@ -292,7 +219,7 @@ services:
       - "18123:8123"
       - "29000:9000"
     environment:
-      CLICKHOUSE_DB: "datalab"
+      CLICKHOUSE_DB: "cameraaberta"
       CLICKHOUSE_USER: "admin"
       CLICKHOUSE_PASSWORD: "admin"
       CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
@@ -326,8 +253,6 @@ services:
         #user user@datalab.com.br pass datalab
       volumes:
         - ./util:/util
-
-
  
 ##################################################
 ### ANALISE E PROCESSAMENTO
@@ -415,12 +340,6 @@ services:
     command:
       - start-dev --import-realm
 
-  postman:
-    image: quay.io/microcks/microcks-postman-runtime:latest
-    platform: linux/amd64
-    container_name: microcks-postman-runtime
-
-
   pgadmin:
     container_name: pgadmin_container
     image: dpage/pgadmin4
@@ -435,8 +354,83 @@ services:
 
 #############################
 ## GENERAL
-
-  
+  airflow-init:
+    <<: *airflow-common
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    # yamllint enable rule:line-length
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_UPGRADE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    user: "0:0"
+    volumes:
+      - ./airflow:/sources
 
 configs:
   flags:
@@ -445,3 +439,5 @@ configs:
 networks:
   datalab:
     driver: bridge
+
+
